---
# tasks file for apache2
- name: install tools
  apt: 
    name: 
      - apache2
      - libapache2-mod-wsgi
    state: latest 
  tags: [ 'packages' ]

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  # If there is a change it will notify handler and trigger
  notify: restart apache2
  tags: [ 'configure' ]

- name: de-activate default apache2 site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2
  tags: [ 'configure' ]

- name: ensure apache2 started
  service: name=apache2 state=started enabled=yes
  tags: [ 'service' ]