---
# tasks file for mysql
- name: install tools
  apt: 
    name: 
      - python-mysqldb
    state: latest
  tags: [ 'packages' ]

- name: install mysql-server
  apt: 
    name: mysql-server 
    state: latest
  tags: [ 'packages' ]

- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = {{ ansible_eth1.ipv4.address }}"
  notify: restart mysql
  tags: [ 'configure' ]

- name: ensure mysql started
  service: name=mysql state=started enabled=yes
  tags: [ 'service' ]

- name: create database
  mysql_db: name={{ db_name }} state=present
  tags: [ 'configure' ]

- name: create user
  mysql_user: name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL 
              host='%' state=present
  tags: [ 'configure' ]