---
# tasks file for nginx
- name: install tools
  apt: 
    name: 
      - python-httplib2
    state: latest
  tags: [ 'packages' ]

- name: install nginx
  apt: 
    name: nginx 
    state: latest 
  tags: [ 'packages' ]

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx
  tags: [ 'configure' ]

- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active
  changed_when: "active.stdout_lines != sites.keys()"
  tags: [ 'configure' ]

- name: de-activate sites
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  loop: "{{ active.stdout_lines|flatten }}"
  when: item not in sites
  notify: restart nginx
  tags: [ 'configure' ]

- name: activate nginx site
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  loop: "{{ sites|dict2items }}"
  notify: restart nginx
  tags: [ 'configure' ]

- name: ensure nginx started
  service: name=nginx state=started enabled=yes
  tags: [ 'service' ]