---
- hosts: database
  become: true
  tasks:
    - name: instal mysql-server
      apt: 
        name: mysql-server 
        state: latest 
        update_cache: yes
    
    - name: ensure mysql started
      service: name=mysql state=started enabled=yes