---
- hosts: loadbalancer
  #sudo in the past. become can take 'yes' as parameter as well
  become: true 
  tasks:
    - name: install nginx
      apt: 
        name: nginx 
        state: latest 
        update_cache: yes
    
   #- name: ensure nginx started
    #  service: name=nginx state=started enabled=yes

    - name: configure nginx
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0755
      notify: restart nginx

    - name: de-activate nginx default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx

    - name: activate nginx demo site
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted