---
- hosts: webserver
  become: true
  tasks:
    - name: install apache2
      apt: 
        name: 
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv
        state: latest 
        update_cache: yes
        